More accomodating when not using NSD

diff --git a/azone b/azone
--- a/azone
+++ b/azone
@@ -8,7 +8,7 @@
 #
 # Source:   https://github.com/nlydv/azone
 # Author:   Neel Yadav
-# Date:     06.27.2021
+# Date:     07.01.2021
 
 VERSION=0.1.1
 COMMAND=$1
@@ -40,10 +40,7 @@ NSD_CONTROL=$(which nsd-control)
 initialize () {
     # || -z $NSD_CONTROL || -z $(which nsd)
     if [[ -z $LDNS_KEYGEN || -z $LDNS_SIGN || -z $LDNS_VERIFY || -z $LDNS_KEY2DS ]]; then
-        echo -e "\n——${red}Error${reset}: NSD and/or ldns command line tools are either not installed or are not accessible from \$PATH\n"
-        exit 13
-    elif [[ ! -d /etc/nsd ]]; then
-        echo -e "\n——${red}Error${reset}: the directory /etc/nsd does not exist\n"
+        echo -e "\n——${red}Error${reset}: ldns command line tools are either not installed or are not accessible from \$PATH\n"
         exit 13
     elif [[ ! $EUID == 0 ]]; then
         echo -e "\n——${red}Error${reset}: azone should only be used with root permissions\n"
@@ -71,6 +68,7 @@ initialize () {
 
 usage () {
     cat <<END
+
 ${ul}USAGE${reset}
     ${bold}azone [command] ZONE${reset}
 
@@ -266,11 +264,16 @@ zonelist () {
             exit 0
             ;;
         -l)
-            sudo $NSD_CONTROL zonestatus | sed -E -e '/state:/d' -e 's/zone:\t//' # @DEV
+            if [[ -x $NSD_CONTROL ]]; then
+                sudo $NSD_CONTROL zonestatus | sed -E -e '/state:/d' -e 's/zone:\t//' # @DEV
+            else
+                echo -e "\n——${red}Error${reset}: NSD not installed or nsd-control not accessible in \$PATH\n"
+                exit 16
+            fi
             exit 0
             ;;
         -*)
-            echo -e "——${red}Error${reset}: invalid command option"
+            echo -e "\n——${red}Error${reset}: invalid command option\n"
             exit 15
             ;;
         *)
@@ -290,6 +293,13 @@ nsd_update () {
         zone=$(echo $k | sed -E 's/(.*)\.signed/\1/')
         name=$(basename $zone)
 
+        # If not using NSD, allow update cron (sans ` && nsd-control reload` command) but do not proceed further
+        if [[ ! -x $NSD_CONTROL ]]; then
+            autosign_cron
+            echo -e "\n——${red}Error${reset}: NSD not installed or nsd-control not accessible in \$PATH\n"
+            exit 16
+        fi
+
         if ! grep -q "zonefile: ${k}" $DEFZONE; then
             echo -e "\nzone:\n\tname: ${name}\n\tzonefile: ${k}" >> $DEFZONE
         fi
@@ -308,10 +318,8 @@ nsd_update () {
     fi
 
     # @TODO: echo error notice + info
-    $NSD_CONTROL reconfig 1> /dev/null || exit      # Tell NSD to check nsd.conf for changes in zone definitions.
-    $NSD_CONTROL reload $1 1> /dev/null || exit     # Tell NSD to reread the actual zonefile(s), changes to which won't get
-                                                    # picked up unless either told to reload (except when reconfig forces
-                                                    # it to check out a newly defined zonefile location).
+    $NSD_CONTROL reconfig 1> /dev/null || exit        # Tell NSD to check nsd.conf for changes to zone definitions.
+    $NSD_CONTROL reload 1> /dev/null || exit          # Tell NSD to reread the defined zonefiles, changes to which don't usually get picked up on reconfig.
 
     [[ $abc == 1 ]] && printf "\n  ${yellow}info${reset} — Unable to symlink data/azone.cron to cron.d"
     echo -e "\n  ${green}Success!${reset} Zone changes relayed to NSD.\n"
@@ -497,8 +505,24 @@ deconfig_main () {
 }
 
 autosign_cron () {
+    if [[ ! -e ${DATADIR}/azone.cron ]]; then
+        cat <<END > ${DATADIR}/azone.cron
+# /etc/cron.d/azone
+#
+# Weekly DNSSEC zone re-signing job generated by azone
+
+SHELL=/bin/bash
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/etc/nsd:/etc/nsd/azone
+
+END
+    fi
+
     if ! grep -q "azone sign ${name}" ${DATADIR}/azone.cron; then
-        echo "1 3 * * 0 root azone sign $(basename ${name}) && nsd-control reload" >> ${DATADIR}/azone.cron
+        if [[ -x $NSD_CONTROL ]]; then
+            echo "$(( $RANDOM % 59 + 1 )) 3 * * 0 root azone sign $(basename ${name}) && nsd-control reload" >> ${DATADIR}/azone.cron
+        else
+            echo "$(( $RANDOM % 59 + 1 )) 3 * * 0 root azone sign $(basename ${name})" >> ${DATADIR}/azone.cron
+        fi
     fi
 
     if [[ -d /etc/cron.d ]]; then
@@ -542,7 +566,7 @@ case $COMMAND in
         exit 0
         ;;
     version)
-        echo "azone v$VERSION — June 2021"
+        echo "azone v$VERSION — July 2021"
         echo "Source: https://github.com/nlydv/azone"
         exit 0
         ;;
@@ -588,3 +612,4 @@ esac
 # 13 — Abort, by script.
 # 14 — Timeout, user input.
 # 15 — Error, user input.
+# 16 — Exogenous, requisite implementation failure.
