Version bump & minor formatting

diff --git a/azone b/azone
--- a/azone
+++ b/azone
@@ -8,9 +8,9 @@
 #
 # Source:   https://github.com/nlydv/azone
 # Author:   Neel Yadav
-# Date:     07.01.2021
+# Date:     09.19.2021
 
-VERSION=0.1.1
+VERSION=0.1.2
 COMMAND=$1
 ZONE=$2
 
@@ -40,17 +40,17 @@ NSD_CONTROL=$(which nsd-control)
 initialize () {
     # || -z $NSD_CONTROL || -z $(which nsd)
     if [[ -z $LDNS_KEYGEN || -z $LDNS_SIGN || -z $LDNS_VERIFY || -z $LDNS_KEY2DS ]]; then
-        echo -e "\n${red}${bold}✖ ${reset}${bold}Error${reset} — ldns command line tools are either not installed or are not accessible from \$PATH\n"
+        echo -e "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — ldns command line tools are either not installed or are not accessible from \$PATH\n"
         exit 13
     elif [[ ! $EUID == 0 ]]; then
-        echo -e "\n${yellow}${bold}！${reset}sudo permissions required\n"
+        echo -e "\n  ${yellow}${bold}！${reset}sudo permissions required\n"
         exit 13
     fi
 
     if [[ $ZONEDIR == "/etc/nsd/azone" ]]; then
         [[ ! -d $ZONEDIR ]] && mkdir $ZONEDIR
     else
-        echo -e "\n${red}${bold}✖ ${reset}${bold}Error${reset} — non-default ZONEDIR directory does not exist — ${ZONEDIR}\n"
+        echo -e "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — non-default ZONEDIR directory does not exist — ${ZONEDIR}\n"
         exit 13
     fi
 
@@ -73,7 +73,7 @@ ${ul}USAGE${reset}
     ${bold}azone [command] ${it}ZONE${xit}${reset}
 
 ${ul}COMMANDS${reset}
-    sign     ${it}ZONE${xit}    Creates a signed zonefile for ${it}ZONE${xit} at ${it}ZONE${xit}.signed
+    sign     ${it}ZONE${xit}    Creates a signed zonefile for ${it}ZONE${xit}
     keygen   ${it}ZONE${xit}    Generates new ksk and zsk keys for ${it}ZONE${xit}
     view     ${it}ZONE${xit}    View info about ${it}ZONE${xit} and its active DS & DNSKEY records
     test     ${it}ZONE${xit}    Locally validates DNSSEC for signed ${it}ZONE${xit}
@@ -133,7 +133,7 @@ keygen () {
         echo -e "\n${bold}Couldn't find zonefile for ${ZONE}.${reset}\n"
         confirm "  Generate keys anyway?" \
             && echo -e "  Ok, brand new set of keys coming up!" \
-            || { echo -e "${yellow}${bold}！${reset}Key generation aborted${reset}\n"; exit 12; }
+            || { echo -e "  ${yellow}${bold}！${reset}Key generation aborted${reset}\n"; exit 12; }
     fi
 
     # Check if a file named 'ksk' or 'zsk' exists in ZONE's dedicated sub-directory within KEYDIR.
@@ -146,7 +146,7 @@ keygen () {
         echo -e "actively used set for this domain. None of the"
         echo -e "pre-existing keys will be deleted though.\n"
         confirm "Continue generating new key set?" \
-            || { echo -e "${yellow}${bold}！${reset}Key generation aborted${reset}.\n"; exit 12; }
+            || { echo -e "  ${yellow}${bold}！${reset}Key generation aborted${reset}.\n"; exit 12; }
         mv ksk ksk.old; mv zsk zsk.old; mv ds ds.old           # Archive previously active pointer files
     fi
 
@@ -156,10 +156,10 @@ keygen () {
     $LDNS_KEYGEN -a ECDSAP256SHA256 -b 1024 $ZONE 1> zsk 2> err.tmp        # Store active ZSK prefix
     mv $(cat ksk).ds ds                                                    # Store DS record for active KSK
     if [[ -z "$(cat err.tmp)" ]]; then
-        printf "\r${green}${bold}✓${reset} Generating keys... ${bold}done${reset}\n\n"
+        printf "\r  ${green}${bold}✓${reset} Generating keys... ${bold}done${reset}\n\n"
         rm err.tmp
     else
-        printf "\n${red}${bold}✖ ${reset}${bold}Error${reset} — something went wrong during key creation\n\n"
+        printf "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — something went wrong during key creation\n\n"
         rm err.tmp
         exit 11
     fi
@@ -177,10 +177,10 @@ sign () {
     [[ -d ${ZONEDIR}/signed ]] || mkdir signed
     [[ -d ${KEYDIR}/${ZONE} ]] && check_pointers
     if ! check_zonefile; then
-        echo -e "\n${red}${bold}✖ ${reset}${bold}Error${reset} — unable to locate zonefile for ${ZONE}\n"
+        echo -e "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — unable to locate zonefile for ${ZONE}\n"
         exit 13
     elif [[ ! -f ${KSK}.private || ! -f ${ZSK}.private ]]; then
-        echo -e "\n${red}${bold}✖ ${reset}${bold}Error${reset} — unable to locate signing keys for ${ZONE}"
+        echo -e "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — unable to locate signing keys for ${ZONE}"
         echo -e "  Try generating a new set of keys: ${bold}azone keygen ${ZONE}${reset}\n"
         exit 13
     elif [[ $(grep --count "SIGNED_ON" $ZONEFILE) == 1 ]]; then
@@ -190,10 +190,10 @@ sign () {
     $LDNS_SIGN -o $ZONE -f $SIGNED -i $inception -e $expiration - $KSK $ZSK < <(sed s/SIGNED_ON/$serial/ $ZONEFILE)
 
     if [[ $? == 0 ]]; then
-        echo -e "\n${green}${bold}✓${reset} ${bold}Signed! ${reset}${serial}\n"
+        echo -e "\n  ${green}${bold}✓${reset} ${bold}Signed! ${reset}${serial}\n"
         exit 0
     else
-        echo -e "\n${red}${bold}✖ ${reset}${bold}Error${reset} — something went wrong while trying to sign ${ZONE}.\n"
+        echo -e "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — something went wrong while trying to sign ${ZONE}.\n"
         exit 11
     fi
 }
@@ -201,7 +201,7 @@ sign () {
 # TEST
 validate () {
     if [[ -z $1 ]]; then
-        echo -e "\n${red}${bold}✖ ${reset}${bold}Error${reset} — no zone given to test\n"
+        echo -e "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — no zone given to test\n"
         exit 15
     elif [[ -n $2 ]]; then
         if [[ $1 == "-g" || $2 == "-g" ]]; then
@@ -210,7 +210,7 @@ validate () {
             local signed=${ZONEDIR}/signed/${zone}.signed
             valcmd="$LDNS_VERIFY -V 0 -k ${DATADIR}/icann.root.key -k ${DATADIR}/hns.root.key -S ${signed}"
         else
-            echo -e "\n${red}${bold}✖ ${reset}${bold}Error${reset} — invalid command option\n"
+            echo -e "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — invalid command option\n"
             exit 15
         fi
     else
@@ -220,13 +220,13 @@ validate () {
     fi
 
     if [[ ! -f ${signed} ]]; then
-        echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — $(basename ${signed}) not found\n"
+        echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — $(basename ${signed}) not found\n"
         exit 13
     elif $valcmd; then
-        echo -e "\n${green}${bold}✓ ${reset}Signed zonefile is valid.${reset}\n"
+        echo -e "\n  ${green}${bold}✓ ${reset}Signed zonefile is valid.${reset}\n"
         exit 0
     else
-        echo -e "\n${yellow}${bold}！${reset}Failed to verify DNSSEC signatures.${reset}\n"
+        echo -e "\n  ${yellow}${bold}！${reset}Failed to verify DNSSEC signatures.${reset}\n"
         exit 11
     fi
 }
@@ -237,7 +237,7 @@ zoneview () {
     if ! check_zonefile; then
         if [[ ! -f ${KSK}.private || ! -f ${ZSK}.private ]]; then
             if ! check_pointers; then
-                echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — no knowledge of zone\n"
+                echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — no knowledge of zone\n"
                 exit 11
             fi
         else
@@ -284,13 +284,13 @@ zonelist () {
                 echo -e "\n${ul}${bold}Zones Served by NSD${reset}"
                 sudo $NSD_CONTROL zonestatus | sed -E -e '/state:/d' -e 's/zone:\t//' -e 's/(.+)/  \1/'; echo ""
             else
-                echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — NSD not installed or nsd-control not accessible in \$PATH\n"
+                echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — NSD not installed or nsd-control not accessible in \$PATH\n"
                 exit 16
             fi
             exit 0
             ;;
         -*)
-            echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — invalid command option\n"
+            echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — invalid command option\n"
             exit 15
             ;;
         *)
@@ -313,7 +313,7 @@ nsd_update () {
         # If not using NSD, allow update cron (sans ` && nsd-control reload` command) but do not proceed further
         if [[ ! -x $NSD_CONTROL ]]; then
             autosign_cron
-            echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — NSD not installed or nsd-control not accessible in \$PATH\n"
+            echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — NSD not installed or nsd-control not accessible in \$PATH\n"
             exit 16
         fi
 
@@ -322,7 +322,7 @@ nsd_update () {
         fi
 
         if ! deconfig_main; then
-            echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — ${name} defined in nsd.conf & couldn't move it to zones.conf\n"
+            echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — ${name} defined in nsd.conf & couldn't move it to zones.conf\n"
             exit 13
         fi
 
@@ -338,8 +338,8 @@ nsd_update () {
     $NSD_CONTROL reconfig 1> /dev/null || exit        # Tell NSD to check nsd.conf for changes to zone definitions.
     $NSD_CONTROL reload 1> /dev/null || exit          # Tell NSD to reread the defined zonefiles, changes to which don't usually get picked up on reconfig.
 
-    [[ $abc == 1 ]] && printf "\n${yellow}${bold}！${reset}Unable to symlink data/azone.cron to cron.d"
-    echo -e "\n${green}${bold}✓${reset} ${bold}Success! ${reset} Zone changes relayed to NSD.\n"
+    [[ $abc == 1 ]] && printf "\n  ${yellow}${bold}！${reset}Unable to symlink data/azone.cron to cron.d"
+    echo -e "\n  ${green}${bold}✓${reset} ${bold}Success! ${reset} Zone changes relayed to NSD.\n"
 
     secure_keys; exit 0
 }
@@ -348,10 +348,10 @@ nsd_update () {
 keyimport () {
     import_keydir=$1
     if [[ -z $import_keydir ]]; then
-        echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — you must specify a directory path where existing keys are located"
+        echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — you must specify a directory path where existing keys are located"
         exit 15
     elif [[ ! -d $import_keydir ]]; then
-        echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — $import_keydir is not a directory"
+        echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — $import_keydir is not a directory"
         exit 15
     else
         cd ${KEYDIR} || exit 13
@@ -406,7 +406,7 @@ get_serial () {
         elif [[ ! -e ${DATADIR}/serial-store ]]; then
             echo 'example.com:0:0' > ${DATADIR}/serial-store
         else
-            echo -e "\n${red}${bold}✖${reset} ${bold}Error${reset} — unable to write to file '${DATADIR}/serial-store'\n"
+            echo -e "\n  ${red}${bold}✖${reset} ${bold}Error${reset} — unable to write to file '${DATADIR}/serial-store'\n"
             exit 13
         fi
     fi
@@ -449,11 +449,11 @@ update_serial () {
 
 check_zonefile () {
     if [[ -z $ZONE ]]; then
-        echo -e "${red}${bold}✖${reset} ${bold}Error${reset} — a zone argument is required in the form of the domain's FQDN"
+        echo -e "  ${red}${bold}✖${reset} ${bold}Error${reset} — a zone argument is required in the form of the domain's FQDN"
         exit 15
     elif [[ ! -f $ZONEFILE ]]; then
         if [[ -f ${ZONEFILE}.zone ]]; then
-            echo -e "${yellow}${bold}！${reset}${bold}Warning${reset}"
+            echo -e "  ${yellow}${bold}！${reset}${bold}Warning${reset}"
             echo -e "\n${bold}No zonefile named ${it}${ZONE}${xit}, but found ${it}${ZONE}.zone${xit} file.${reset}"
             echo -e "By default, ${ul}azone${reset} assumes the associated zonefile for ZONE is simply named ${it}<FQDN>${xit}"
             echo -e "rather than the common naming schemes of ${it}<FQDN>.zone${xit} or ${it}<FQDN>.txt${xit} for"
@@ -491,7 +491,7 @@ check_pointers () {
         local ZSK; ZSK=$(cat zsk)
 
         if [[ ! -f ${KSK}.key || ! -f ${ZSK}.key ]]; then
-            echo -e "${red}${bold}✖ ${reset}${bold}Error${reset} — failed to regenerate KSK/ZSK pointer files"
+            echo -e "  ${red}${bold}✖ ${reset}${bold}Error${reset} — failed to regenerate KSK/ZSK pointer files"
             return 1
         else
             $LDNS_KEY2DS -n "$(cat ksk).key" | sed -E 's/\t[0-9]+(\tIN\tDS)/\1/' > ds   # Generate DS rr from active KSK
@@ -511,7 +511,7 @@ confirm() {
             return 0
             ;;
         *)
-            [[ $? -gt 128 ]] && echo -e "\n${yellow}${bold}！${reset}Response timeout (1m)\n" && exit 14
+            [[ $? -gt 128 ]] && echo -e "\n  ${yellow}${bold}！${reset}Response timeout (1m)\n" && exit 14
             return 1
             ;;
     esac
@@ -588,7 +588,7 @@ calc_expire () {
         expiration=$(date -u -j -f "%a %b %d %T %Z %Y" "$(date -u -j -v+36d -v+12H)" "+%Y%m%d%H%M02")
     # Assume the worst
     else
-        echo -e "\n${red}${bold}✖ ${reset}${bold}Y2K38${reset} — time is but a relative property of existence and an ephemeral illusion of the universe\n"
+        echo -e "\n  ${red}${bold}✖ ${reset}${bold}Y2K38${reset} — time is but a relative property of existence and an ephemeral illusion of the universe\n"
         exit 16
     fi
 }
@@ -612,7 +612,7 @@ case $COMMAND in
         exit 0
         ;;
     version)
-        echo "azone v$VERSION — July 2021"
+        echo "azone v$VERSION — September 2021"
         echo "Source: https://github.com/nlydv/azone"
         exit 0
         ;;
@@ -647,7 +647,7 @@ case $COMMAND in
                 newzone $2
                 ;;
             *)
-                echo -e "\n${red}${bold}✖ ${reset}${bold}Error${reset} — unknown command\n"
+                echo -e "\n  ${red}${bold}✖ ${reset}${bold}Error${reset} — unknown command\n"
                 exit 15
                 ;;
         esac
